#Para o projeto os pacotes seguintes serão necessários
library(tidyverse)
library(naniar)
library(caret)
library(h2o)
library(dplyr)
library(tidyr)
library(lubridate)
library(skimr)
library(naniar)
library(transplantr)
library(readxl)
library(assertive)
library(testthat)
